export const ONBOARDING_GAMEPLAY_DEMO_MS = 5000;
export const ONBOARDING_DEMO_PHASE_SWITCH_START_MS = 600;
export const ONBOARDING_DEMO_PHASE_SWITCH_END_MS = 1400;
export const ONBOARDING_DEMO_PHASE_BALL_START_MS = 1400;
export const ONBOARDING_DEMO_PHASE_BOUNCE_MS = 2600;
export const ONBOARDING_DEMO_PHASE_FADE_START_MS = 4500;
export const ONBOARDING_DEMO_RIGHT_TRAMPOLINE_TARGET_ANGLE = 0.48;
export const ONBOARDING_DEMO_BALL_LAUNCH_ANGLE = 0.18;
export const ONBOARDING_DEMO_ELECTRIC_IMPACT_VISIBLE_MS = 420;

export const ONBOARDING_DEMO_TYPING_TITLE_START_MS = 0;
export const ONBOARDING_DEMO_TYPING_TITLE_DURATION_MS = 800;
export const ONBOARDING_DEMO_TYPING_SUBTITLE_START_MS = 900;
export const ONBOARDING_DEMO_TYPING_SUBTITLE_DURATION_MS = 1000;
export const ONBOARDING_DEMO_TYPING_DESCRIPTION_START_MS = 2000;
export const ONBOARDING_DEMO_TYPING_DESCRIPTION_DURATION_MS = 2000;
