export const DUAL_TRAMPOLINE_LEFT_START_ANGLE = Math.PI;
export const DUAL_TRAMPOLINE_RIGHT_START_ANGLE = 0;
export const DUAL_TRAMPOLINE_WIDTH_SCALE = 0.82;
export const DUAL_TRAMPOLINE_SPEED_PER_FRAME = 0.045;
export const DUAL_TRAMPOLINE_MIN_SPEED_SCALE = 0.25;
export const DUAL_TRAMPOLINE_MAX_SPEED_SCALE = 1.33;
