// src/constants/visualAssets.ts

export const sprBallPlayerDefault = '/assets/visual/sprites/spr-ball-player-default.svg';
export const sprPaddlePlayerDefault = '/assets/visual/sprites/spr-paddle-player-default.svg';
export const sprBrickBasicRedNormal = '/assets/visual/bricks/spr-brick-basic-red-normal.svg';
export const sprBrickBasicBlueNormal = '/assets/visual/bricks/spr-brick-basic-blue-normal.svg';
export const sprBrickBasicGreenNormal = '/assets/visual/bricks/spr-brick-basic-green-normal.svg';
export const sprBrickBasicYellowNormal = '/assets/visual/bricks/spr-brick-basic-yellow-normal.svg';
export const sprBrickBasicPurpleNormal = '/assets/visual/bricks/spr-brick-basic-purple-normal.svg';
export const vfxCountdownCircleOverlay = '/assets/visual/vfx/vfx-countdown-circle-overlay.svg';
export const vfxCountdownSparkOverlay = '/assets/visual/vfx/vfx-countdown-spark-overlay.svg';
export const vfxLevelUpStarOverlay = '/assets/visual/vfx/vfx-level-up-star-overlay.svg';
export const vfxLevelUpTwirlOverlay = '/assets/visual/vfx/vfx-level-up-twirl-overlay.svg';
export const vfxGameOverRipSmoke = '/assets/visual/vfx/vfx-game-over-rip-smoke.svg';
export const sprPowerupMultiballOrb = '/assets/visual/powerups/spr-powerup-multiball-orb.svg';
export const sprPowerupWidePaddle = '/assets/visual/powerups/spr-powerup-wide-paddle.svg';
export const sprPowerupSlowBall = '/assets/visual/powerups/spr-powerup-slow-ball.svg';
export const sprPowerupLaserFan = '/assets/visual/powerups/spr-powerup-laser-fan.svg';
export const uiAppBrowserFavicon = '/assets/visual/ui/ui-app-browser-favicon.svg';
export const uiPwaAppIcon = '/assets/visual/ui/ui-pwa-app-icon.svg';
export const sprBallPlayerHighContrastDefault = '/assets/visual/sprites/spr-ball-player-high-contrast-default.svg';
export const sprPaddlePlayerHighContrastDefault = '/assets/visual/sprites/spr-paddle-player-high-contrast-default.svg';
export const sprBrickBasicRedHighContrastNormal = '/assets/visual/bricks/spr-brick-basic-red-high-contrast-normal.svg';
export const sprBrickBasicBlueHighContrastNormal = '/assets/visual/bricks/spr-brick-basic-blue-high-contrast-normal.svg';
export const sprBrickBasicGreenHighContrastNormal = '/assets/visual/bricks/spr-brick-basic-green-high-contrast-normal.svg';
export const sprBrickBasicYellowHighContrastNormal = '/assets/visual/bricks/spr-brick-basic-yellow-high-contrast-normal.svg';
export const sprBrickBasicPurpleHighContrastNormal = '/assets/visual/bricks/spr-brick-basic-purple-high-contrast-normal.svg';
export const vfxCountdownCircleHighContrastOverlay = '/assets/visual/vfx/vfx-countdown-circle-high-contrast-overlay.svg';
export const vfxCountdownSparkHighContrastOverlay = '/assets/visual/vfx/vfx-countdown-spark-high-contrast-overlay.svg';
export const vfxLevelUpStarHighContrastOverlay = '/assets/visual/vfx/vfx-level-up-star-high-contrast-overlay.svg';
export const vfxLevelUpTwirlHighContrastOverlay = '/assets/visual/vfx/vfx-level-up-twirl-high-contrast-overlay.svg';
export const vfxGameOverRipHighContrastSmoke = '/assets/visual/vfx/vfx-game-over-rip-high-contrast-smoke.svg';
export const sprPowerupMultiballOrbHighContrast = '/assets/visual/powerups/spr-powerup-multiball-orb-high-contrast.svg';
export const sprPowerupWidePaddleHighContrast = '/assets/visual/powerups/spr-powerup-wide-paddle-high-contrast.svg';
export const sprPowerupSlowBallHighContrast = '/assets/visual/powerups/spr-powerup-slow-ball-high-contrast.svg';
export const sprPowerupLaserFanHighContrast = '/assets/visual/powerups/spr-powerup-laser-fan-high-contrast.svg';
export const sprBallPlayerSunsetDefault = '/assets/visual/sprites/spr-ball-player-sunset-default.svg';
export const sprPaddlePlayerSunsetDefault = '/assets/visual/sprites/spr-paddle-player-sunset-default.svg';
export const sprBrickBasicRedSunsetNormal = '/assets/visual/bricks/spr-brick-basic-red-sunset-normal.svg';
export const sprBrickBasicBlueSunsetNormal = '/assets/visual/bricks/spr-brick-basic-blue-sunset-normal.svg';
export const sprBrickBasicGreenSunsetNormal = '/assets/visual/bricks/spr-brick-basic-green-sunset-normal.svg';
export const sprBrickBasicYellowSunsetNormal = '/assets/visual/bricks/spr-brick-basic-yellow-sunset-normal.svg';
export const sprBrickBasicPurpleSunsetNormal = '/assets/visual/bricks/spr-brick-basic-purple-sunset-normal.svg';
export const vfxCountdownCircleSunsetOverlay = '/assets/visual/vfx/vfx-countdown-circle-sunset-overlay.svg';
export const vfxCountdownSparkSunsetOverlay = '/assets/visual/vfx/vfx-countdown-spark-sunset-overlay.svg';
export const vfxLevelUpStarSunsetOverlay = '/assets/visual/vfx/vfx-level-up-star-sunset-overlay.svg';
export const vfxLevelUpTwirlSunsetOverlay = '/assets/visual/vfx/vfx-level-up-twirl-sunset-overlay.svg';
export const vfxGameOverRipSunsetSmoke = '/assets/visual/vfx/vfx-game-over-rip-sunset-smoke.svg';
export const sprPowerupMultiballOrbSunset = '/assets/visual/powerups/spr-powerup-multiball-orb-sunset.svg';
export const sprPowerupWidePaddleSunset = '/assets/visual/powerups/spr-powerup-wide-paddle-sunset.svg';
export const sprPowerupSlowBallSunset = '/assets/visual/powerups/spr-powerup-slow-ball-sunset.svg';
export const sprPowerupLaserFanSunset = '/assets/visual/powerups/spr-powerup-laser-fan-sunset.svg';

export type VisualAssetGroup = 'sprite' | 'brick' | 'powerup' | 'vfx' | 'ui';

export interface VisualAssetCatalogEntry {
  id: string;
  variableName: string;
  path: string;
  group: VisualAssetGroup;
  semanticRole: string;
  state: string;
  width: number;
  height: number;
  usage: string;
}

export const VISUAL_ASSET_PATHS = {
  sprBallPlayerDefault,
  sprPaddlePlayerDefault,
  sprBrickBasicRedNormal,
  sprBrickBasicBlueNormal,
  sprBrickBasicGreenNormal,
  sprBrickBasicYellowNormal,
  sprBrickBasicPurpleNormal,
  vfxCountdownCircleOverlay,
  vfxCountdownSparkOverlay,
  vfxLevelUpStarOverlay,
  vfxLevelUpTwirlOverlay,
  vfxGameOverRipSmoke,
  sprPowerupMultiballOrb,
  sprPowerupWidePaddle,
  sprPowerupSlowBall,
  sprPowerupLaserFan,
  uiAppBrowserFavicon,
  uiPwaAppIcon,
  sprBallPlayerHighContrastDefault,
  sprPaddlePlayerHighContrastDefault,
  sprBrickBasicRedHighContrastNormal,
  sprBrickBasicBlueHighContrastNormal,
  sprBrickBasicGreenHighContrastNormal,
  sprBrickBasicYellowHighContrastNormal,
  sprBrickBasicPurpleHighContrastNormal,
  vfxCountdownCircleHighContrastOverlay,
  vfxCountdownSparkHighContrastOverlay,
  vfxLevelUpStarHighContrastOverlay,
  vfxLevelUpTwirlHighContrastOverlay,
  vfxGameOverRipHighContrastSmoke,
  sprPowerupMultiballOrbHighContrast,
  sprPowerupWidePaddleHighContrast,
  sprPowerupSlowBallHighContrast,
  sprPowerupLaserFanHighContrast,
  sprBallPlayerSunsetDefault,
  sprPaddlePlayerSunsetDefault,
  sprBrickBasicRedSunsetNormal,
  sprBrickBasicBlueSunsetNormal,
  sprBrickBasicGreenSunsetNormal,
  sprBrickBasicYellowSunsetNormal,
  sprBrickBasicPurpleSunsetNormal,
  vfxCountdownCircleSunsetOverlay,
  vfxCountdownSparkSunsetOverlay,
  vfxLevelUpStarSunsetOverlay,
  vfxLevelUpTwirlSunsetOverlay,
  vfxGameOverRipSunsetSmoke,
  sprPowerupMultiballOrbSunset,
  sprPowerupWidePaddleSunset,
  sprPowerupSlowBallSunset,
  sprPowerupLaserFanSunset,
} as const;

export const VISUAL_ASSET_CATALOG = [
  {
    id: 'spr-ball-player-default',
    variableName: 'sprBallPlayerDefault',
    path: sprBallPlayerDefault,
    group: 'sprite',
    semanticRole: 'ball',
    state: 'normal',
    width: 16,
    height: 16,
    usage: 'Esfera principal',
  },
  {
    id: 'spr-paddle-player-default',
    variableName: 'sprPaddlePlayerDefault',
    path: sprPaddlePlayerDefault,
    group: 'sprite',
    semanticRole: 'paddle',
    state: 'normal',
    width: 96,
    height: 16,
    usage: 'Raquete padrão',
  },
  {
    id: 'spr-brick-basic-red-normal',
    variableName: 'sprBrickBasicRedNormal',
    path: sprBrickBasicRedNormal,
    group: 'brick',
    semanticRole: 'brick-red',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco básico vermelho',
  },
  {
    id: 'spr-brick-basic-blue-normal',
    variableName: 'sprBrickBasicBlueNormal',
    path: sprBrickBasicBlueNormal,
    group: 'brick',
    semanticRole: 'brick-blue',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco básico azul',
  },
  {
    id: 'spr-brick-basic-green-normal',
    variableName: 'sprBrickBasicGreenNormal',
    path: sprBrickBasicGreenNormal,
    group: 'brick',
    semanticRole: 'brick-green',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco básico verde',
  },
  {
    id: 'spr-brick-basic-yellow-normal',
    variableName: 'sprBrickBasicYellowNormal',
    path: sprBrickBasicYellowNormal,
    group: 'brick',
    semanticRole: 'brick-yellow',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco básico amarelo',
  },
  {
    id: 'spr-brick-basic-purple-normal',
    variableName: 'sprBrickBasicPurpleNormal',
    path: sprBrickBasicPurpleNormal,
    group: 'brick',
    semanticRole: 'brick-purple',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco básico roxo',
  },
  {
    id: 'vfx-countdown-circle-overlay',
    variableName: 'vfxCountdownCircleOverlay',
    path: vfxCountdownCircleOverlay,
    group: 'vfx',
    semanticRole: 'countdown-circle',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Anel da contagem inicial',
  },
  {
    id: 'vfx-countdown-spark-overlay',
    variableName: 'vfxCountdownSparkOverlay',
    path: vfxCountdownSparkOverlay,
    group: 'vfx',
    semanticRole: 'countdown-spark',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Faísca da contagem inicial',
  },
  {
    id: 'vfx-level-up-star-overlay',
    variableName: 'vfxLevelUpStarOverlay',
    path: vfxLevelUpStarOverlay,
    group: 'vfx',
    semanticRole: 'level-up-star',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Estrela de subida de fase',
  },
  {
    id: 'vfx-level-up-twirl-overlay',
    variableName: 'vfxLevelUpTwirlOverlay',
    path: vfxLevelUpTwirlOverlay,
    group: 'vfx',
    semanticRole: 'level-up-twirl',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Espiral de subida de fase',
  },
  {
    id: 'vfx-game-over-rip-smoke',
    variableName: 'vfxGameOverRipSmoke',
    path: vfxGameOverRipSmoke,
    group: 'vfx',
    semanticRole: 'game-over-rip',
    state: 'smoke',
    width: 180,
    height: 180,
    usage: 'Fumaça de fim de jogo',
  },
  {
    id: 'spr-powerup-multiball-orb',
    variableName: 'sprPowerupMultiballOrb',
    path: sprPowerupMultiballOrb,
    group: 'powerup',
    semanticRole: 'multiball',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up multiball',
  },
  {
    id: 'spr-powerup-wide-paddle',
    variableName: 'sprPowerupWidePaddle',
    path: sprPowerupWidePaddle,
    group: 'powerup',
    semanticRole: 'wide-paddle',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up raquete ampla',
  },
  {
    id: 'spr-powerup-slow-ball',
    variableName: 'sprPowerupSlowBall',
    path: sprPowerupSlowBall,
    group: 'powerup',
    semanticRole: 'slow-ball',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up bola lenta',
  },
  {
    id: 'spr-powerup-laser-fan',
    variableName: 'sprPowerupLaserFan',
    path: sprPowerupLaserFan,
    group: 'powerup',
    semanticRole: 'laser-fan',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up laser em leque',
  },
  {
    id: 'ui-app-browser-favicon',
    variableName: 'uiAppBrowserFavicon',
    path: uiAppBrowserFavicon,
    group: 'ui',
    semanticRole: 'favicon',
    state: 'normal',
    width: 32,
    height: 32,
    usage: 'Ícone do navegador',
  },
  {
    id: 'ui-pwa-app-icon',
    variableName: 'uiPwaAppIcon',
    path: uiPwaAppIcon,
    group: 'ui',
    semanticRole: 'pwa-icon',
    state: 'normal',
    width: 512,
    height: 512,
    usage: 'Ícone instalável da PWA',
  },
  {
    id: 'spr-ball-player-high-contrast-default',
    variableName: 'sprBallPlayerHighContrastDefault',
    path: sprBallPlayerHighContrastDefault,
    group: 'sprite',
    semanticRole: 'ball-high-contrast',
    state: 'normal',
    width: 16,
    height: 16,
    usage: 'Esfera alto contraste',
  },
  {
    id: 'spr-paddle-player-high-contrast-default',
    variableName: 'sprPaddlePlayerHighContrastDefault',
    path: sprPaddlePlayerHighContrastDefault,
    group: 'sprite',
    semanticRole: 'paddle-high-contrast',
    state: 'normal',
    width: 96,
    height: 16,
    usage: 'Raquete alto contraste',
  },
  {
    id: 'spr-brick-basic-red-high-contrast-normal',
    variableName: 'sprBrickBasicRedHighContrastNormal',
    path: sprBrickBasicRedHighContrastNormal,
    group: 'brick',
    semanticRole: 'brick-red-high-contrast',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco vermelho alto contraste',
  },
  {
    id: 'spr-brick-basic-blue-high-contrast-normal',
    variableName: 'sprBrickBasicBlueHighContrastNormal',
    path: sprBrickBasicBlueHighContrastNormal,
    group: 'brick',
    semanticRole: 'brick-blue-high-contrast',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco azul alto contraste',
  },
  {
    id: 'spr-brick-basic-green-high-contrast-normal',
    variableName: 'sprBrickBasicGreenHighContrastNormal',
    path: sprBrickBasicGreenHighContrastNormal,
    group: 'brick',
    semanticRole: 'brick-green-high-contrast',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco verde alto contraste',
  },
  {
    id: 'spr-brick-basic-yellow-high-contrast-normal',
    variableName: 'sprBrickBasicYellowHighContrastNormal',
    path: sprBrickBasicYellowHighContrastNormal,
    group: 'brick',
    semanticRole: 'brick-yellow-high-contrast',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco amarelo alto contraste',
  },
  {
    id: 'spr-brick-basic-purple-high-contrast-normal',
    variableName: 'sprBrickBasicPurpleHighContrastNormal',
    path: sprBrickBasicPurpleHighContrastNormal,
    group: 'brick',
    semanticRole: 'brick-purple-high-contrast',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco roxo alto contraste',
  },
  {
    id: 'vfx-countdown-circle-high-contrast-overlay',
    variableName: 'vfxCountdownCircleHighContrastOverlay',
    path: vfxCountdownCircleHighContrastOverlay,
    group: 'vfx',
    semanticRole: 'countdown-circle-high-contrast',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Anel da contagem inicial alto contraste',
  },
  {
    id: 'vfx-countdown-spark-high-contrast-overlay',
    variableName: 'vfxCountdownSparkHighContrastOverlay',
    path: vfxCountdownSparkHighContrastOverlay,
    group: 'vfx',
    semanticRole: 'countdown-spark-high-contrast',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Faísca da contagem inicial alto contraste',
  },
  {
    id: 'vfx-level-up-star-high-contrast-overlay',
    variableName: 'vfxLevelUpStarHighContrastOverlay',
    path: vfxLevelUpStarHighContrastOverlay,
    group: 'vfx',
    semanticRole: 'level-up-star-high-contrast',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Estrela de subida de fase alto contraste',
  },
  {
    id: 'vfx-level-up-twirl-high-contrast-overlay',
    variableName: 'vfxLevelUpTwirlHighContrastOverlay',
    path: vfxLevelUpTwirlHighContrastOverlay,
    group: 'vfx',
    semanticRole: 'level-up-twirl-high-contrast',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Espiral de subida de fase alto contraste',
  },
  {
    id: 'vfx-game-over-rip-high-contrast-smoke',
    variableName: 'vfxGameOverRipHighContrastSmoke',
    path: vfxGameOverRipHighContrastSmoke,
    group: 'vfx',
    semanticRole: 'game-over-rip-high-contrast',
    state: 'smoke',
    width: 180,
    height: 180,
    usage: 'Fumaça de fim de jogo alto contraste',
  },
  {
    id: 'spr-powerup-multiball-orb-high-contrast',
    variableName: 'sprPowerupMultiballOrbHighContrast',
    path: sprPowerupMultiballOrbHighContrast,
    group: 'powerup',
    semanticRole: 'multiball-high-contrast',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up multiball alto contraste',
  },
  {
    id: 'spr-powerup-wide-paddle-high-contrast',
    variableName: 'sprPowerupWidePaddleHighContrast',
    path: sprPowerupWidePaddleHighContrast,
    group: 'powerup',
    semanticRole: 'wide-paddle-high-contrast',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up raquete ampla alto contraste',
  },
  {
    id: 'spr-powerup-slow-ball-high-contrast',
    variableName: 'sprPowerupSlowBallHighContrast',
    path: sprPowerupSlowBallHighContrast,
    group: 'powerup',
    semanticRole: 'slow-ball-high-contrast',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up bola lenta alto contraste',
  },
  {
    id: 'spr-powerup-laser-fan-high-contrast',
    variableName: 'sprPowerupLaserFanHighContrast',
    path: sprPowerupLaserFanHighContrast,
    group: 'powerup',
    semanticRole: 'laser-fan-high-contrast',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up laser em leque alto contraste',
  },
  {
    id: 'spr-ball-player-sunset-default',
    variableName: 'sprBallPlayerSunsetDefault',
    path: sprBallPlayerSunsetDefault,
    group: 'sprite',
    semanticRole: 'ball-sunset',
    state: 'normal',
    width: 16,
    height: 16,
    usage: 'Esfera sunset',
  },
  {
    id: 'spr-paddle-player-sunset-default',
    variableName: 'sprPaddlePlayerSunsetDefault',
    path: sprPaddlePlayerSunsetDefault,
    group: 'sprite',
    semanticRole: 'paddle-sunset',
    state: 'normal',
    width: 96,
    height: 16,
    usage: 'Raquete sunset',
  },
  {
    id: 'spr-brick-basic-red-sunset-normal',
    variableName: 'sprBrickBasicRedSunsetNormal',
    path: sprBrickBasicRedSunsetNormal,
    group: 'brick',
    semanticRole: 'brick-red-sunset',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco vermelho sunset',
  },
  {
    id: 'spr-brick-basic-blue-sunset-normal',
    variableName: 'sprBrickBasicBlueSunsetNormal',
    path: sprBrickBasicBlueSunsetNormal,
    group: 'brick',
    semanticRole: 'brick-blue-sunset',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco azul sunset',
  },
  {
    id: 'spr-brick-basic-green-sunset-normal',
    variableName: 'sprBrickBasicGreenSunsetNormal',
    path: sprBrickBasicGreenSunsetNormal,
    group: 'brick',
    semanticRole: 'brick-green-sunset',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco verde sunset',
  },
  {
    id: 'spr-brick-basic-yellow-sunset-normal',
    variableName: 'sprBrickBasicYellowSunsetNormal',
    path: sprBrickBasicYellowSunsetNormal,
    group: 'brick',
    semanticRole: 'brick-yellow-sunset',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco amarelo sunset',
  },
  {
    id: 'spr-brick-basic-purple-sunset-normal',
    variableName: 'sprBrickBasicPurpleSunsetNormal',
    path: sprBrickBasicPurpleSunsetNormal,
    group: 'brick',
    semanticRole: 'brick-purple-sunset',
    state: 'normal',
    width: 48,
    height: 20,
    usage: 'Bloco roxo sunset',
  },
  {
    id: 'vfx-countdown-circle-sunset-overlay',
    variableName: 'vfxCountdownCircleSunsetOverlay',
    path: vfxCountdownCircleSunsetOverlay,
    group: 'vfx',
    semanticRole: 'countdown-circle-sunset',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Anel da contagem inicial sunset',
  },
  {
    id: 'vfx-countdown-spark-sunset-overlay',
    variableName: 'vfxCountdownSparkSunsetOverlay',
    path: vfxCountdownSparkSunsetOverlay,
    group: 'vfx',
    semanticRole: 'countdown-spark-sunset',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Faísca da contagem inicial sunset',
  },
  {
    id: 'vfx-level-up-star-sunset-overlay',
    variableName: 'vfxLevelUpStarSunsetOverlay',
    path: vfxLevelUpStarSunsetOverlay,
    group: 'vfx',
    semanticRole: 'level-up-star-sunset',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Estrela de subida de fase sunset',
  },
  {
    id: 'vfx-level-up-twirl-sunset-overlay',
    variableName: 'vfxLevelUpTwirlSunsetOverlay',
    path: vfxLevelUpTwirlSunsetOverlay,
    group: 'vfx',
    semanticRole: 'level-up-twirl-sunset',
    state: 'overlay',
    width: 180,
    height: 180,
    usage: 'Espiral de subida de fase sunset',
  },
  {
    id: 'vfx-game-over-rip-sunset-smoke',
    variableName: 'vfxGameOverRipSunsetSmoke',
    path: vfxGameOverRipSunsetSmoke,
    group: 'vfx',
    semanticRole: 'game-over-rip-sunset',
    state: 'smoke',
    width: 180,
    height: 180,
    usage: 'Fumaça de fim de jogo sunset',
  },
  {
    id: 'spr-powerup-multiball-orb-sunset',
    variableName: 'sprPowerupMultiballOrbSunset',
    path: sprPowerupMultiballOrbSunset,
    group: 'powerup',
    semanticRole: 'multiball-sunset',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up multiball sunset',
  },
  {
    id: 'spr-powerup-wide-paddle-sunset',
    variableName: 'sprPowerupWidePaddleSunset',
    path: sprPowerupWidePaddleSunset,
    group: 'powerup',
    semanticRole: 'wide-paddle-sunset',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up raquete ampla sunset',
  },
  {
    id: 'spr-powerup-slow-ball-sunset',
    variableName: 'sprPowerupSlowBallSunset',
    path: sprPowerupSlowBallSunset,
    group: 'powerup',
    semanticRole: 'slow-ball-sunset',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up bola lenta sunset',
  },
  {
    id: 'spr-powerup-laser-fan-sunset',
    variableName: 'sprPowerupLaserFanSunset',
    path: sprPowerupLaserFanSunset,
    group: 'powerup',
    semanticRole: 'laser-fan-sunset',
    state: 'collectible',
    width: 24,
    height: 24,
    usage: 'Power-up laser em leque sunset',
  },
] as const satisfies readonly VisualAssetCatalogEntry[];

export const RUNTIME_VISUAL_ASSET_PATHS = Object.values(VISUAL_ASSET_PATHS);
