// src/utils/visualAssetResolver.ts
import {
  IMAGE_SET_HIGH_CONTRAST,
  IMAGE_SET_RETRO_DEFAULT,
  IMAGE_SET_SUNSET_CABINET,
  type ImageSetId,
} from '../constants/appearance';
import {
  sprBallPlayerDefault,
  sprBallPlayerHighContrastDefault,
  sprBallPlayerSunsetDefault,
  sprBrickBasicBlueHighContrastNormal,
  sprBrickBasicBlueNormal,
  sprBrickBasicBlueSunsetNormal,
  sprBrickBasicGreenHighContrastNormal,
  sprBrickBasicGreenNormal,
  sprBrickBasicGreenSunsetNormal,
  sprBrickBasicPurpleHighContrastNormal,
  sprBrickBasicPurpleNormal,
  sprBrickBasicPurpleSunsetNormal,
  sprBrickBasicRedHighContrastNormal,
  sprBrickBasicRedNormal,
  sprBrickBasicRedSunsetNormal,
  sprBrickBasicYellowHighContrastNormal,
  sprBrickBasicYellowNormal,
  sprBrickBasicYellowSunsetNormal,
  sprPaddlePlayerDefault,
  sprPaddlePlayerHighContrastDefault,
  sprPaddlePlayerSunsetDefault,
  sprPowerupLaserFan,
  sprPowerupLaserFanHighContrast,
  sprPowerupLaserFanSunset,
  sprPowerupMultiballOrb,
  sprPowerupMultiballOrbHighContrast,
  sprPowerupMultiballOrbSunset,
  sprPowerupSlowBall,
  sprPowerupSlowBallHighContrast,
  sprPowerupSlowBallSunset,
  sprPowerupWidePaddle,
  sprPowerupWidePaddleHighContrast,
  sprPowerupWidePaddleSunset,
  uiAppBrowserFavicon,
  uiPwaAppIcon,
  vfxCountdownCircleHighContrastOverlay,
  vfxCountdownCircleOverlay,
  vfxCountdownCircleSunsetOverlay,
  vfxCountdownSparkHighContrastOverlay,
  vfxCountdownSparkOverlay,
  vfxCountdownSparkSunsetOverlay,
  vfxGameOverRipHighContrastSmoke,
  vfxGameOverRipSmoke,
  vfxGameOverRipSunsetSmoke,
  vfxLevelUpStarHighContrastOverlay,
  vfxLevelUpStarOverlay,
  vfxLevelUpStarSunsetOverlay,
  vfxLevelUpTwirlHighContrastOverlay,
  vfxLevelUpTwirlOverlay,
  vfxLevelUpTwirlSunsetOverlay,
} from '../constants/visualAssets';

export const GAME_VISUAL_ASSET_ROLES = {
  ball: 'ball',
  paddle: 'paddle',
  brickRed: 'brickRed',
  brickBlue: 'brickBlue',
  brickGreen: 'brickGreen',
  brickYellow: 'brickYellow',
  brickPurple: 'brickPurple',
  powerupMultiball: 'powerupMultiball',
  powerupWidePaddle: 'powerupWidePaddle',
  powerupSlowBall: 'powerupSlowBall',
  powerupLaserFan: 'powerupLaserFan',
  countdownCircleOverlay: 'countdownCircleOverlay',
  countdownSparkOverlay: 'countdownSparkOverlay',
  levelUpStarOverlay: 'levelUpStarOverlay',
  levelUpTwirlOverlay: 'levelUpTwirlOverlay',
  gameOverRipSmoke: 'gameOverRipSmoke',
  appBrowserFavicon: 'appBrowserFavicon',
  pwaAppIcon: 'pwaAppIcon',
} as const;

export type GameVisualAssetRole =
  (typeof GAME_VISUAL_ASSET_ROLES)[keyof typeof GAME_VISUAL_ASSET_ROLES];

export const GAME_VISUAL_ASSETS_BY_IMAGE_SET = {
  [IMAGE_SET_RETRO_DEFAULT]: {
    [GAME_VISUAL_ASSET_ROLES.ball]: sprBallPlayerDefault,
    [GAME_VISUAL_ASSET_ROLES.paddle]: sprPaddlePlayerDefault,
    [GAME_VISUAL_ASSET_ROLES.brickRed]: sprBrickBasicRedNormal,
    [GAME_VISUAL_ASSET_ROLES.brickBlue]: sprBrickBasicBlueNormal,
    [GAME_VISUAL_ASSET_ROLES.brickGreen]: sprBrickBasicGreenNormal,
    [GAME_VISUAL_ASSET_ROLES.brickYellow]: sprBrickBasicYellowNormal,
    [GAME_VISUAL_ASSET_ROLES.brickPurple]: sprBrickBasicPurpleNormal,
    [GAME_VISUAL_ASSET_ROLES.powerupMultiball]: sprPowerupMultiballOrb,
    [GAME_VISUAL_ASSET_ROLES.powerupWidePaddle]: sprPowerupWidePaddle,
    [GAME_VISUAL_ASSET_ROLES.powerupSlowBall]: sprPowerupSlowBall,
    [GAME_VISUAL_ASSET_ROLES.powerupLaserFan]: sprPowerupLaserFan,
    [GAME_VISUAL_ASSET_ROLES.countdownCircleOverlay]: vfxCountdownCircleOverlay,
    [GAME_VISUAL_ASSET_ROLES.countdownSparkOverlay]: vfxCountdownSparkOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpStarOverlay]: vfxLevelUpStarOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpTwirlOverlay]: vfxLevelUpTwirlOverlay,
    [GAME_VISUAL_ASSET_ROLES.gameOverRipSmoke]: vfxGameOverRipSmoke,
    [GAME_VISUAL_ASSET_ROLES.appBrowserFavicon]: uiAppBrowserFavicon,
    [GAME_VISUAL_ASSET_ROLES.pwaAppIcon]: uiPwaAppIcon,
  },
  [IMAGE_SET_HIGH_CONTRAST]: {
    [GAME_VISUAL_ASSET_ROLES.ball]: sprBallPlayerHighContrastDefault,
    [GAME_VISUAL_ASSET_ROLES.paddle]: sprPaddlePlayerHighContrastDefault,
    [GAME_VISUAL_ASSET_ROLES.brickRed]: sprBrickBasicRedHighContrastNormal,
    [GAME_VISUAL_ASSET_ROLES.brickBlue]: sprBrickBasicBlueHighContrastNormal,
    [GAME_VISUAL_ASSET_ROLES.brickGreen]: sprBrickBasicGreenHighContrastNormal,
    [GAME_VISUAL_ASSET_ROLES.brickYellow]: sprBrickBasicYellowHighContrastNormal,
    [GAME_VISUAL_ASSET_ROLES.brickPurple]: sprBrickBasicPurpleHighContrastNormal,
    [GAME_VISUAL_ASSET_ROLES.powerupMultiball]: sprPowerupMultiballOrbHighContrast,
    [GAME_VISUAL_ASSET_ROLES.powerupWidePaddle]: sprPowerupWidePaddleHighContrast,
    [GAME_VISUAL_ASSET_ROLES.powerupSlowBall]: sprPowerupSlowBallHighContrast,
    [GAME_VISUAL_ASSET_ROLES.powerupLaserFan]: sprPowerupLaserFanHighContrast,
    [GAME_VISUAL_ASSET_ROLES.countdownCircleOverlay]: vfxCountdownCircleHighContrastOverlay,
    [GAME_VISUAL_ASSET_ROLES.countdownSparkOverlay]: vfxCountdownSparkHighContrastOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpStarOverlay]: vfxLevelUpStarHighContrastOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpTwirlOverlay]: vfxLevelUpTwirlHighContrastOverlay,
    [GAME_VISUAL_ASSET_ROLES.gameOverRipSmoke]: vfxGameOverRipHighContrastSmoke,
    [GAME_VISUAL_ASSET_ROLES.appBrowserFavicon]: uiAppBrowserFavicon,
    [GAME_VISUAL_ASSET_ROLES.pwaAppIcon]: uiPwaAppIcon,
  },
  [IMAGE_SET_SUNSET_CABINET]: {
    [GAME_VISUAL_ASSET_ROLES.ball]: sprBallPlayerSunsetDefault,
    [GAME_VISUAL_ASSET_ROLES.paddle]: sprPaddlePlayerSunsetDefault,
    [GAME_VISUAL_ASSET_ROLES.brickRed]: sprBrickBasicRedSunsetNormal,
    [GAME_VISUAL_ASSET_ROLES.brickBlue]: sprBrickBasicBlueSunsetNormal,
    [GAME_VISUAL_ASSET_ROLES.brickGreen]: sprBrickBasicGreenSunsetNormal,
    [GAME_VISUAL_ASSET_ROLES.brickYellow]: sprBrickBasicYellowSunsetNormal,
    [GAME_VISUAL_ASSET_ROLES.brickPurple]: sprBrickBasicPurpleSunsetNormal,
    [GAME_VISUAL_ASSET_ROLES.powerupMultiball]: sprPowerupMultiballOrbSunset,
    [GAME_VISUAL_ASSET_ROLES.powerupWidePaddle]: sprPowerupWidePaddleSunset,
    [GAME_VISUAL_ASSET_ROLES.powerupSlowBall]: sprPowerupSlowBallSunset,
    [GAME_VISUAL_ASSET_ROLES.powerupLaserFan]: sprPowerupLaserFanSunset,
    [GAME_VISUAL_ASSET_ROLES.countdownCircleOverlay]: vfxCountdownCircleSunsetOverlay,
    [GAME_VISUAL_ASSET_ROLES.countdownSparkOverlay]: vfxCountdownSparkSunsetOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpStarOverlay]: vfxLevelUpStarSunsetOverlay,
    [GAME_VISUAL_ASSET_ROLES.levelUpTwirlOverlay]: vfxLevelUpTwirlSunsetOverlay,
    [GAME_VISUAL_ASSET_ROLES.gameOverRipSmoke]: vfxGameOverRipSunsetSmoke,
    [GAME_VISUAL_ASSET_ROLES.appBrowserFavicon]: uiAppBrowserFavicon,
    [GAME_VISUAL_ASSET_ROLES.pwaAppIcon]: uiPwaAppIcon,
  },
} as const satisfies Record<ImageSetId, Record<GameVisualAssetRole, string>>;

export function resolveGameVisualAssetPath(
  imageSetId: ImageSetId,
  role: GameVisualAssetRole,
): string {
  return GAME_VISUAL_ASSETS_BY_IMAGE_SET[imageSetId][role];
}

export function getRuntimeVisualAssetPathsForImageSet(
  imageSetId: ImageSetId,
): string[] {
  return Object.values(GAME_VISUAL_ASSETS_BY_IMAGE_SET[imageSetId]);
}
