// scripts/materialize-ci-env.mjs
import { chmodSync, writeFileSync } from 'node:fs';
import { registryEntries } from './load-project-env.mjs';

const ENV_FILE_MODE = 0o600;
const DEFAULTS = {
  BRIKAYA_CLOUDFLARE_PAGES_PROJECT_NAME: 'brikaya-live',
  BRIKAYA_CLOUDFLARE_PAGES_BRANCH: 'main',
  BRIKAYA_CLOUDFLARE_PAGES_OUTPUT_DIR: 'dist',
  BRIKAYA_CLOUDFLARE_PAGES_CUSTOM_DOMAIN: 'brikaya.com',
  BRIKAYA_CLOUDFLARE_PAGES_PREVIEW_PROJECT_NAME: 'brikaya-dev',
  BRIKAYA_CLOUDFLARE_PAGES_PREVIEW_DOMAIN: 'dev.brikaya.com',
  BRIKAYA_CLOUDFLARE_PAGES_PREVIEW_BRANCH: 'preview',
  BRIKAYA_CLOUDFLARE_ZONE_NAME: 'brikaya.com',
  BRIKAYA_INDEXNOW_ENDPOINT: 'https://yandex.com/indexnow',
  BRIKAYA_INDEXNOW_PUBLIC_ROOT: 'dist',
  BRIKAYA_INDEXNOW_SITEMAP: 'dist/sitemap.xml',
  BRIKAYA_INDEXNOW_DRY_RUN: 'true',
  BRIKAYA_GOOGLE_SEARCH_CONSOLE_PROPERTY: 'sc-domain:brikaya.com',
  BRIKAYA_INDEXNOW_KEY: 'ci-placeholder-indexnow-key',
};

function quoteValue(value) {
  return /^[A-Za-z0-9_./:@+-]+$/.test(value) ? value : JSON.stringify(value);
}

function run() {
  const entries = registryEntries();
  const lines = ['# Generated by scripts/materialize-ci-env.mjs'];

  for (const entry of entries) {
    const value = process.env[entry.name] || DEFAULTS[entry.name];
    if (!value && entry.required) {
      throw new Error(`Variável obrigatória ausente para CI: ${entry.name}`);
    }
    if (value) {
      lines.push(`${entry.name}=${quoteValue(value)}`);
    }
  }

  const content = `${lines.join('\n')}\n`;
  writeFileSync('.env', content, { mode: ENV_FILE_MODE });
  chmodSync('.env', ENV_FILE_MODE);
  console.log('CI env materializado em .env (valores sensíveis omitidos dos logs).');
}

run();
